//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id { get; set; }
        public int A_Grade { get; set; }
        public int A__Grade { get; set; }
        public int B__Grade { get; set; }
        public int B_Grade { get; set; }
        public int B__Grade1 { get; set; }
        public int C__Grade { get; set; }
        public int C_Grade { get; set; }
        public int C__Grade1 { get; set; }
        public int F_Grade { get; set; }
    }
}
